### ISSUE TITLE
[Feature] Integration with existing CVE API

### ISSUE THREAD

**Issue by PVM-NL** [renatoalmeidaoliveira/nbrisk#1]
Thanks for creating this plugin. 

I wonder if you are going to automate it more with the existing devices in Netbox?
Is it possible to link it to existing CVE API like:
https://nvd.nist.gov/developers/vulnerabilities#:~:text=The%20CVE%20Change%20History%20API%20is%20used%20to,to%20easily%20monitor%20when%20and%20why%20vulnerabilities%20change.

Perhaps you are already planning this in advance of course as the app is still in BETA release.

**Comment by renatoalmeidaoliveira** [comment]
Thank you very much for the idea!!!
Already deployed the first part, missing the links from the Vulnerability List.

**Comment by renatoalmeidaoliveira** [comment]
Released in 0.2.0
