### ISSUE TITLE
Adding Submodules in NetBox

### ISSUE THREAD

**Issue by yousefii** [renatoalmeidaoliveira/nbrisk#11]
Hello;
I just started using NetBox and I have an issue with adding modules.
Actually, I have a Module that has 2 submodules. When I add this module to a device I can't add a daughterboard to the main modules.
 How can I add this Module and then add 1 daughterboard to it?
 Is that impossible or have I missed something here?

**Comment by renatoalmeidaoliveira** [comment]
Hello @yousefii this seen like a NetBox question, not about the NBRisk, for that you might get better help in:
 - [NetBox Slack Channel](https://netdev.chat/)
 - [NetBox Discussions](https://github.com/netbox-community/netbox/discussions)
