### ISSUE TITLE
Bug: Sorting by affected assets doesn't work

### ISSUE THREAD

**Issue by alegru** [renatoalmeidaoliveira/nbrisk#18]
Sorting by affected assets on the vulnerabilities page doesn't work. That's a bummer, but sorting preferences are unfortunately stored in the user profile. Upon refreshing or visiting the page again, the user gets greeted by the following error page:
```
<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword 'affected_assets' into field. Choices are: created, custom_field_data, cve, cvssaccessComplexity, cvssaccessVector, cvssauthentication, cvssavailabilityImpact, cvssbaseScore, cvssconfidentialityImpact, cvssintegrityImpact, description, id, journal_entries, last_updated, name, notes, tagged_items, tags, vulnerability_assignments

Python version: 3.10.6
NetBox version: 3.4.10
```
The user has to clear the table preferences manually in this case.

**Comment by renatoalmeidaoliveira** [comment]
@alegru  Thank you for the report.
Please update for 34.0.1 if you are in Netbox 3.4.x or 35.0.2 if in 3.5.x
