### ISSUE TITLE
Add extra options for assessments

### ISSUE THREAD

**Issue by PVM-NL** [renatoalmeidaoliveira/nbrisk#2]
Hi,

I wonder if you going to extend it more with options like?
As i might be wrong ofcourse with this but might be useful:
- Actions Recommended
- Responsibility / Target Date
- Actions Taken.

Maybe/Extra:
- option to link to existing ITSM ticket number? 

Drawings:
![image](https://user-images.githubusercontent.com/120473446/221807406-774a9f97-da53-45b5-a1b1-7992601be3eb.png)
![image](https://user-images.githubusercontent.com/120473446/221807423-09b4ed88-5da8-4a71-b954-d230adb08d1f.png)

**Comment by renatoalmeidaoliveira** [comment]
@PVM-NL  I've focused in the implementation of the 800-30 that doesn't implements controls, but that kind of model is something that I fell like its missing.
About the `Actions Taken` I was thinkin in the Journal model.
And that seccond image you post what is its source?

**Comment by PVM-NL** [comment]
https://resources.infosecinstitute.com/certification/cissp-risk-management-concepts-2/

**Comment by renatoalmeidaoliveira** [comment]
Added a Control model to the Plugin
