### ISSUE TITLE
Documentation Wrong?

### ISSUE THREAD

**Issue by adamboutcher** [renatoalmeidaoliveira/nbrisk#20]
`# echo "NbRisk==^35.0.0" >> local_requirements.txt `

I think should be

`# echo "NbRisk>=35.0.0" >> local_requirements.txt `

**Comment by renatoalmeidaoliveira** [comment]
Thank you, it's endeed incorrect.
But my idea for versioning is the major version following netbox so just `> 35.0
0` isn't enought.
I'm searching for a good way to do that too.

**Comment by Urth** [comment]
You can use `NbRisk~=35.0` or `NbRisk==35.*` for that.
https://peps.python.org/pep-0440/#examples
