### ISSUE TITLE
ImportError: cannot import name 'get_plugin_config' from 'extras.plugins' after 3.5.8 Upgrade

### ISSUE THREAD

**Issue by ekrichbaum** [renatoalmeidaoliveira/nbrisk#22]
ImportError: cannot import name 'get_plugin_config' from 'extras.plugins' (/opt/netbox/netbox/extras/plugins/__init__.py)

Related to https://github.com/netbox-community/netbox/commit/f5a1f83f9fa9d98c945d21eb0f7ccb8cd37fbf59

get_plugin_config was moved to utils.

**Comment by renatoalmeidaoliveira** [comment]
Fixed upgrade to 35.1.0.
Thanks for your contribution.
