### ISSUE TITLE
"Vulnerability Assignments > +Add" results in "requested page does not exist"

### ISSUE THREAD

**Issue by adestis-bm** [renatoalmeidaoliveira/nbrisk#25]
I recently added this plugin to our NetBox setup (v4.0.5 and v4.0.6). 
My colleagues started testing it, and discovered, that under "Vulnerability Assignments" the "+Add" botton results in the following error:

```
/plugins/nb_risk/vulnerability-assignments/add/ 
The requested page does not exist. 
```

![grafik](https://github.com/renatoalmeidaoliveira/nbrisk/assets/70651878/7b6b3d28-6019-4390-bbfa-54e4535dc834)

All other "+Add" bottons ("Threat Sources", "Threat Events", "Vulnerabilities", "Rists", and "Controls") do work.

I'm no Django specialist to know how to debug this.
Could someone assist me with locating this problem, please?!

**Comment by renatoalmeidaoliveira** [comment]
Hello @adestis-bm , the Vulnerability Assignments models works very similar to the Contact Assignments, you need to go the desired model ( the vulnerable one) and click in the button Assign Vulnerability on the to right of the page, there shouldn't be a add button on the Vulnerabilty Assignments view.
The other way to assign vulnerabilities is using the import view.

**Comment by adestis-bm** [comment]
Thank You for Your quick response!

That's what we "see":
![grafik](https://github.com/renatoalmeidaoliveira/nbrisk/assets/70651878/6ff7a407-e92f-4492-ba9c-92ef9303698a)

Also there is an entry in `urls.py`:
![grafik](https://github.com/renatoalmeidaoliveira/nbrisk/assets/70651878/0aaefb0e-eea2-4592-bd80-ec1728562966)

Bug?

**Comment by adestis-bm** [comment]
The "Assugn Vulnerability" botton is there, and it is working... I just tested it.
![grafik](https://github.com/renatoalmeidaoliveira/nbrisk/assets/70651878/f775de22-1461-4646-a187-0bb9a568d249)

So just the "+ Add" botton shouldn't be there:
![grafik](https://github.com/renatoalmeidaoliveira/nbrisk/assets/70651878/4a51723d-a8ac-4b81-8021-bafea3bc5e3b)

**Comment by renatoalmeidaoliveira** [comment]
Thanks that "Add" button is a bug. gonna remove it.
To add a Vulnerability Assignment please go to the desired model and click on the Assign Vulnerability button.

**Comment by adestis-bm** [comment]
Looks like I found another problem: the "Changelog" option results in a "Server Error: TemplateDoesNotExist":
![grafik](https://github.com/renatoalmeidaoliveira/nbrisk/assets/70651878/f99a55ab-ca2d-4327-a35e-3ca65bcae38e)

![grafik](https://github.com/renatoalmeidaoliveira/nbrisk/assets/70651878/8e95248a-5195-4319-8db9-bd74bae1e3b8)
