### ISSUE TITLE
Link CVEs to Platform

### ISSUE THREAD

**Issue by cyberndj** [renatoalmeidaoliveira/nbrisk#3]
Howdy,
I've noticed that some CVEs can be associated with software versions/platforms of devices.
Would it be possible to add referencing CVEs to platforms so you could see in the platform views what CVEs are associated?

Also, as a bonus, could you also use the platform association to populate the affected devices based on device/platform?

**Comment by cyberndj** [comment]
>  an environment may have multiple versions of that platform, so the end user should map several platforms one for each version

This is the way we do it in our environment. We are also using ansible to upgrade our devices (just switches for now) and to update NetBox with the new platform. I know associating a CVE to multiple Platforms might be tedious, but I think it might be the best way to go (and you might be able to use tools like Ansible to automate it).

![image](https://user-images.githubusercontent.com/16530317/226481920-60265867-8818-43a5-8eed-cab5670a4fd2.png)

**Comment by renatoalmeidaoliveira** [comment]
Thanks for sharing the way you map the platforms.
For the NIST CVE API I'm using this doc as reference:
https://www.signalscorps.com/blog/2023/building-cve2stix-1-cpes-cves-nvd-api/

And the  GET request is built that way:
cpe:2.3:<part>:<vendor>:<product>:
<version>:<update>:<edition>:<language>:<sw_edition>:<target_sw:>:<target_hw>:<other>

With that schema I need to be able split the platform = <product> from its version and using only the platform name isn't much reliable...

But it may be a good option to use platforms this way but calling custom fields from they.

**Comment by cyberndj** [comment]
Howdy, 
Just for some clarity, this FR is to add assigning CVE's to Platforms manually to allow the basic hand-jamming associations.
The GET method is still very good, but I thing just falls a bit out of scope of this FR.
v/r
-Jake

**Comment by renatoalmeidaoliveira** [comment]
Ohh I see @cyberndj, about the Vulnerability Assignments, in the next release it may be configuration based, so the users gonna able to assign vulnerabilities to any model
